const g7 = [
  // --- 新学期新目标 (80) ---
  ['plan','/plæn/','计划','n.','I have a new plan for this term.','我这学期有一个新计划。'],
  ['goal','/ɡoʊl/','目标','n.','My goal is to pass the exam.','我的目标是通过考试。'],
  ['timetable','/ˈtaɪmteɪbl/','课程表','n.','Check the timetable for your classes.','查看你的课程表。'],
  ['subject','/ˈsʌbdʒɪkt/','科目','n.','Math is my favorite subject.','数学是我最喜欢的科目。'],
  ['grade','/ɡreɪd/','成绩','n.','She got good grades in the exam.','她考试取得了好成绩。'],
  ['score','/skɔːr/','分数','n.','His score was the highest in class.','他的分数是班上最高的。'],
  ['exam','/ɪɡˈzæm/','考试','n.','We will have an exam next week.','我们下周有考试。'],
  ['pass','/pæs/','通过','v.','I hope I can pass the exam.','我希望能通过考试。'],
  ['fail','/feɪl/','失败','v.','He might fail the math test.','他可能数学考试不及格。'],
  ['study','/ˈstʌdi/','学习','v.','I study English every day.','我每天学习英语。'],
  ['review','/rɪˈvjuː/','复习','v.','Let us review the lessons.','让我们复习功课。'],
  ['prepare','/prɪˈper/','准备','v.','She is preparing for the exam.','她正在准备考试。'],
  ['focus','/ˈfoʊkəs/','专注','v.','Focus on your studies.','专注于你的学习。'],
  ['progress','/ˈprɒɡres/','进步','n.','You have made great progress.','你取得了很大的进步。'],
  ['improve','/ɪmˈpruːv/','提高','v.','I want to improve my English.','我想提高我的英语。'],
  ['achieve','/əˈtʃiːv/','实现','v.','I want to achieve my goal.','我想实现我的目标。'],
  ['effort','/ˈefərt/','努力','n.','Success requires effort.','成功需要努力。'],
  ['determination','/dɪˌtɜːrməˈneɪʃn/','决心','n.','She has strong determination.','她有很强的决心。'],
  ['challenge','/ˈtʃælɪndʒ/','挑战','n.','Life is full of challenges.','生活充满了挑战。'],
  ['overcome','/ˌoʊvərˈkʌm/','克服','v.','We can overcome any difficulty.','我们能克服任何困难。'],
  ['confident','/ˈkɒnfɪdənt/','自信的','adj.','She is confident about her ability.','她对自己的能力很自信。'],
  ['confidence','/ˈkɒnfɪdəns/','信心','n.','Have confidence in yourself.','对自己有信心。'],
  ['ambition','/æmˈbɪʃn/','抱负','n.','His ambition is to be a doctor.','他的抱负是成为一名医生。'],
  ['diligent','/ˈdɪlɪdʒənt/','勤奋的','adj.','She is a diligent student.','她是一个勤奋的学生。'],
  ['perseverance','/ˌpɜːrsəˈvɪrəns/','毅力','n.','Success needs perseverance.','成功需要毅力。'],
  ['strategy','/ˈstrætədʒi/','策略','n.','We need a good study strategy.','我们需要一个好的学习策略。'],
  ['organize','/ˈɔːrɡənaɪz/','组织','v.','He organized the class meeting.','他组织了班会。'],
  ['time','/taɪm/','时间','n.','Time is precious.','时间是宝贵的。'],
  ['manage','/ˈmænɪdʒ/','管理','v.','Learn to manage your time.','学会管理你的时间。'],
  ['deadline','/ˈdedlaɪn/','截止日期','n.','The deadline is next Friday.','截止日期是下周五。'],
  ['assignment','/əˈsaɪnmənt/','作业','n.','Finish your assignment tonight.','今晚完成你的作业。'],
  ['project','/ˈprɒdʒekt/','项目','n.','Our science project is interesting.','我们的科学项目很有趣。'],
  ['presentation','/ˌprezənˈteɪʃn/','展示','n.','She gave a great presentation.','她做了一个精彩的展示。'],
  ['experiment','/ɪkˈsperɪmənt/','实验','n.','The experiment was successful.','实验成功了。'],
  ['analysis','/əˈnæləsɪs/','分析','n.','His analysis was correct.','他的分析是正确的。'],
  ['research','/ˈriːsɜːrtʃ/','研究','n.','He is doing research on history.','他在做历史研究。'],
  ['knowledge','/ˈnɒlɪdʒ/','知识','n.','Knowledge is power.','知识就是力量。'],
  ['improvement','/ɪmˈpruːvmənt/','改进','n.','I see great improvement in your work.','我看到你的作业有很大进步。'],
  ['capable','/ˈkeɪpəbl/','有能力的','adj.','She is capable of anything.','她无所不能。'],
  ['capability','/ˌkeɪpəˈbɪləti/','能力','n.','His capability is unquestionable.','他的能力毋庸置疑。'],
  ['practice','/ˈpræktɪs/','练习','n.','Practice makes perfect.','熟能生巧。'],
  ['exercise','/ˈeksərsaɪz/','练习','n.','Do the exercises on page 20.','做第20页的练习。'],
  ['translate','/trænsˈleɪt/','翻译','v.','Can you translate this sentence?','你能翻译这句话吗？'],
  ['pronunciation','/prəˌnʌnsiˈeɪʃn/','发音','n.','Her pronunciation is excellent.','她的发音很棒。'],
  ['grammar','/ˈɡræmər/','语法','n.','English grammar is complex.','英语语法很复杂。'],
  ['vocabulary','/voʊˈkæbjəleri/','词汇','n.','I need to expand my vocabulary.','我需要扩大词汇量。'],
  ['dictionary','/ˈdɪkʃəneri/','字典','n.','Look it up in the dictionary.','在字典里查一下。'],
  ['notebook','/ˈnoʊtbʊk/','笔记本','n.','Write it in your notebook.','写在你的笔记本上。'],
  ['textbook','/ˈtekstbʊk/','课本','n.','Open your textbooks to page 50.','打开课本到50页。'],
  ['workbook','/ˈwɜːrkbʊk/','练习册','n.','Complete the workbook exercises.','完成练习册上的习题。'],
  ['pencil','/ˈpensl/','铅笔','n.','Can I borrow your pencil?','我能借你的铅笔吗？'],
  ['library','/ˈlaɪbreri/','图书馆','n.','I study at the library.','我在图书馆学习。'],
  ['classroom','/ˈklæsruːm/','教室','n.','Our classroom is clean.','我们的教室很干净。'],
  ['playground','/ˈpleɪɡraʊnd/','操场','n.','We play football on the playground.','我们在操场上踢足球。'],
  ['uniform','/ˈjuːnɪfɔːrm/','校服','n.','We wear uniforms on Monday.','我们周一穿校服。'],
  ['bell','/bel/','铃','n.','The bell rang for class.','上课铃响了。'],
  ['blackboard','/ˈblækbɔːrd/','黑板','n.','The teacher wrote on the blackboard.','老师在黑板上写字。'],
  ['chalk','/tʃɔːk/','粉笔','n.','She picked up a piece of chalk.','她拿起一支粉笔。'],
  ['eraser','/ɪˈreɪsər/','橡皮擦','n.','Use the eraser to clean the board.','用黑板擦擦黑板。'],
  ['prioritize','/praɪˈɔːrɪtaɪz/','优先处理','v.','You must prioritize your homework.','你必须优先做作业。'],
  ['overdue','/ˌoʊvərˈduː/','逾期的','adj.','Your homework is overdue.','你的作业逾期了。'],
  ['extracurricular','/ˌekstrəkəˈrɪkjələr/','课外的','adj.','I join extracurricular activities.','我参加课外活动。'],
  ['competition','/ˌkɒmpəˈtɪʃn/','比赛','n.','We won the English competition.','我们赢了英语比赛。'],
  ['contest','/ˈkɒntest/','竞赛','n.','She entered the speech contest.','她参加了演讲比赛。'],
  ['champion','/ˈtʃæmpiən/','冠军','n.','He is the champion of the race.','他是赛跑冠军。'],
  ['volunteer','/ˌvɒlənˈtɪr/','志愿者','n.','She is a volunteer teacher.','她是一名志愿教师。'],
  ['semester','/sɪˈmestər/','学期','n.','The new semester begins in September.','新学期九月开始。'],
  ['curriculum','/kəˈrɪkjələm/','课程','n.','The school updated its curriculum.','学校更新了课程。'],
  ['campus','/ˈkæmpəs/','校园','n.','Our campus is very beautiful.','我们的校园很美。'],
  ['dormitory','/ˈdɔːrmətɔːri/','宿舍','n.','He lives in the dormitory.','他住在宿舍。'],
  ['canteen','/kænˈtiːn/','食堂','n.','The canteen serves lunch.','食堂供应午餐。'],
  ['enroll','/ɪnˈroʊl/','注册','v.','I enrolled in the English class.','我注册了英语班。'],
  ['tuition','/tuːˈɪʃn/','学费','n.','The tuition fee is high.','学费很高。'],
  ['scholarship','/ˈskɒlərʃɪp/','奖学金','n.','She won a scholarship.','她获得了奖学金。'],
  ['diploma','/dɪˈploʊmə/','文凭','n.','He received his diploma.','他获得了文凭。'],
  ['academic','/ˌækəˈdemɪk/','学术的','adj.','Academic performance is important.','学业表现很重要。'],
  ['bachelor','/ˈbætʃələr/','学士','n.','She earned a bachelor degree.','她获得了学士学位。'],
  ['master','/ˈmæstər/','硕士','n.','He is studying for his master degree.','他正在攻读硕士学位。'],
  ['graduate','/ˈɡrædʒueɪt/','毕业','v.','She will graduate next year.','她明年毕业。'],
  ['headmaster','/ˌhedˈmæstər/','校长','n.','The headmaster gave a speech.','校长发表了演讲。'],
  ['classmate','/ˈklæsmeɪt/','同学','n.','My classmates are friendly.','我的同学很友好。'],
  ['deskmate','/ˈdeskmeɪt/','同桌','n.','My deskmate helps me a lot.','我的同桌帮了我很多。'],
  ['teacher','/ˈtiːtʃər/','老师','n.','My teacher is very kind.','我的老师很和蔼。'],
  ['lesson','/ˈlesn/','课','n.','This lesson is difficult.','这节课很难。'],
  ['principal','/ˈprɪnsəpl/','校长','n.','The principal gave a speech.','校长发表了讲话。'],
  ['boarding','/ˈbɔːrdɪŋ/','寄宿','n.','He lives in boarding school.','他在寄宿学校。'],
  ['seminar','/ˈsemɪnɑːr/','研讨会','n.','We attended a seminar.','我们参加了研讨会。'],
  ['workshop','/ˈwɜːrkʃɒp/','讲习班','n.','She joined a workshop.','她参加了讲习班。'],
  ['lecture','/ˈlektʃər/','讲座','n.','The lecture was interesting.','讲座很有趣。'],
  // --- 日常生活 (120) ---
  ['breakfast','/ˈbrekfəst/','早餐','n.','I have breakfast at seven.','我七点吃早餐。'],
  ['lunch','/lʌntʃ/','午餐','n.','Let us have lunch together.','我们一起吃午餐吧。'],
  ['dinner','/ˈdɪnər/','晚餐','n.','Dinner is ready.','晚餐准备好了。'],
  ['wake','/weɪk/','醒来','v.','I wake up at six.','我六点起床。'],
  ['sleep','/sliːp/','睡觉','v.','I sleep eight hours a day.','我每天睡八小时。'],
  ['commute','/kəˈmjuːt/','通勤','v.','He commutes to school by bus.','他乘公交车上学。'],
  ['homework','/ˈhoʊmwɜːrk/','家庭作业','n.','I finished my homework.','我完成了作业。'],
  ['chore','/tʃɔːr/','家务','n.','Washing dishes is a chore.','洗碗是一项家务。'],
  ['laundry','/ˈlɔːndri/','洗衣','n.','The laundry is done.','衣服洗好了。'],
  ['grocery','/ˈɡroʊsəri/','杂货','n.','I need to buy groceries.','我需要买杂货。'],
  ['appointment','/əˈpɔɪntmənt/','约会','n.','I have an appointment tomorrow.','我明天有约会。'],
  ['shower','/ˈʃaʊər/','淋浴','n.','I take a shower every morning.','我每天早上淋浴。'],
  ['break','/breɪk/','休息','n.','Let us take a break.','我们休息一下。'],
  ['housework','/ˈhaʊswɜːrk/','家务','n.','She helps with housework.','她帮忙做家务。'],
  ['dishwasher','/ˈdɪʃwɒʃər/','洗碗机','n.','The dishwasher is broken.','洗碗机坏了。'],
  ['microwave','/ˈmaɪkroʊweɪv/','微波炉','n.','Heat it in the microwave.','用微波炉加热。'],
  ['refrigerator','/rɪˈfrɪdʒəreɪtər/','冰箱','n.','Put it in the refrigerator.','把它放冰箱里。'],
  ['furniture','/ˈfɜːrnɪtʃər/','家具','n.','We need new furniture.','我们需要新家具。'],
  ['curtain','/ˈkɜːrtn/','窗帘','n.','Close the curtains.','关上窗帘。'],
  ['carpet','/ˈkɑːrpɪt/','地毯','n.','The carpet is clean.','地毯很干净。'],
  ['pillow','/ˈpɪloʊ/','枕头','n.','I need a new pillow.','我需要一个新枕头。'],
  ['blanket','/ˈblæŋkɪt/','毯子','n.','The blanket is warm.','毯子很暖和。'],
  ['mattress','/ˈmætrəs/','床垫','n.','The mattress is comfortable.','床垫很舒服。'],
  ['tired','/ˈtaɪərd/','疲倦的','adj.','I am very tired today.','我今天很累。'],
  ['energetic','/ˌenərˈdʒetɪk/','精力充沛的','adj.','She is always energetic.','她总是精力充沛。'],
  ['mood','/muːd/','心情','n.','I am in a good mood.','我心情很好。'],
  ['happy','/ˈhæpi/','快乐的','adj.','She is happy today.','她今天很开心。'],
  ['sad','/sæd/','悲伤的','adj.','Do not be sad.','不要难过。'],
  ['angry','/ˈæŋɡri/','生气的','adj.','He is angry about the news.','他对这个消息很生气。'],
  ['excited','/ɪkˈsaɪtɪd/','兴奋的','adj.','The children are excited.','孩子们很兴奋。'],
  ['bored','/bɔːrd/','无聊的','adj.','I am bored with this movie.','这部电影让我觉得无聊。'],
  ['weekend','/ˈwiːkend/','周末','n.','What are you doing this weekend?','你这周末做什么？'],
  ['weekday','/ˈwiːkdeɪ/','工作日','n.','I work on weekdays.','我在工作日工作。'],
  ['morning','/ˈmɔːrnɪŋ/','早晨','n.','Good morning!','早上好！'],
  ['afternoon','/ˌæftərˈnuːn/','下午','n.','Good afternoon!','下午好！'],
  ['evening','/ˈiːvnɪŋ/','傍晚','n.','Good evening!','晚上好！'],
  ['midnight','/ˈmɪdnaɪt/','午夜','n.','He woke up at midnight.','他午夜醒来。'],
  ['sunrise','/ˈsʌnraɪz/','日出','n.','The sunrise is beautiful.','日出很美。'],
  ['sunset','/ˈsʌnset/','日落','n.','We watched the sunset.','我们看了日落。'],
  ['schedule','/ˈskedʒuːl/','日程','n.','What is your schedule today?','你今天的日程是什么？'],
  ['planner','/ˈplænər/','计划本','n.','Write it in your planner.','写在你的计划本上。'],
  ['reminder','/rɪˈmaɪndər/','提醒','n.','Set a reminder for the meeting.','为会议设置提醒。'],
  ['phone','/foʊn/','电话','n.','Answer the phone.','接电话。'],
  ['mobile','/ˈmoʊbl/','手机','n.','My mobile is dead.','我的手机没电了。'],
  ['key','/kiː/','钥匙','n.','Where are my keys?','我的钥匙在哪？'],
  ['wallet','/ˈwɒlɪt/','钱包','n.','I lost my wallet.','我丢了钱包。'],
  ['backpack','/ˈbækpæk/','背包','n.','My backpack is heavy.','我的背包很重。'],
  ['suitcase','/ˈsuːtkeɪs/','手提箱','n.','Pack your suitcase.','收拾你的手提箱。'],
  ['umbrella','/ʌmˈbrelə/','雨伞','n.','Take an umbrella.','带把伞。'],
  ['grab','/ɡræb/','抓','v.','Grab your coat.','拿上你的外套。'],
  ['pack','/pæk/','打包','v.','Pack your bags.','收拾你的行李。'],
  ['unpack','/ˌʌnˈpæk/','打开行李','v.','Unpack your suitcase.','打开你的行李箱。'],
  ['closet','/ˈklɒzɪt/','衣柜','n.','Hang it in the closet.','把它挂在衣柜里。'],
  ['wardrobe','/ˈwɔːrdroʊb/','衣橱','n.','She has a large wardrobe.','她有一个大衣橱。'],
  ['iron','/ˈaɪərn/','熨烫','v.','Iron the shirt.','熨烫衬衫。'],
  ['fold','/foʊld/','折叠','v.','Fold the clothes.','叠衣服。'],
  ['hang','/hæŋ/','挂','v.','Hang the coat here.','把外套挂这里。'],
  ['label','/ˈleɪbl/','标签','n.','Check the label.','检查标签。'],
  ['receipt','/rɪˈsiːt/','收据','n.','Keep the receipt.','保留收据。'],
  ['invoice','/ˈɪnvɔɪs/','发票','n.','Here is your invoice.','这是你的发票。'],
  ['cash','/kæʃ/','现金','n.','I paid in cash.','我付了现金。'],
  ['change','/tʃeɪndʒ/','零钱','n.','Here is your change.','这是找零。'],
  ['coin','/kɔɪn/','硬币','n.','He collects coins.','他收集硬币。'],
  ['price','/praɪs/','价格','n.','What is the price?','价格是多少？'],
  ['cost','/kɔːst/','成本','n.','The cost is high.','成本很高。'],
  ['expense','/ɪkˈspens/','开销','n.','Cut down on expenses.','减少开支。'],
  ['save','/seɪv/','节省','v.','Save money for the future.','为未来存钱。'],
  ['spend','/spend/','花费','v.','She spends a lot on clothes.','她在衣服上花很多钱。'],
  ['waste','/weɪst/','浪费','v.','Do not waste food.','不要浪费食物。'],
  ['thrifty','/ˈθrɪfti/','节俭的','adj.','She is a thrifty person.','她是个节俭的人。'],
  ['neighbor','/ˈneɪbər/','邻居','n.','Our neighbor is friendly.','我们的邻居很友好。'],
  ['community','/kəˈmjuːnəti/','社区','n.','Our community is quiet.','我们的社区很安静。'],
  ['neighborhood','/ˈneɪbərhʊd/','街区','n.','This neighborhood is safe.','这个街区很安全。'],
  ['park','/pɑːrk/','公园','n.','Let us go to the park.','我们去公园吧。'],
  ['garden','/ˈɡɑːrdn/','花园','n.','The garden is beautiful.','花园很美。'],
  ['hospital','/ˈhɒspɪtl/','医院','n.','He works at the hospital.','他在医院工作。'],
  ['clinic','/ˈklɪnɪk/','诊所','n.','The clinic is near here.','诊所就在附近。'],
  ['pharmacy','/ˈfɑːrməsi/','药房','n.','I need to go to the pharmacy.','我需要去药房。'],
  ['dentist','/ˈdentɪst/','牙医','n.','I visit the dentist twice a year.','我每年看两次牙医。'],
  ['medicine','/ˈmedsn/','药','n.','Take this medicine.','吃这个药。'],
  ['comfortable','/ˈkʌmftəbl/','舒适的','adj.','This chair is comfortable.','这把椅子很舒服。'],
  ['uncomfortable','/ʌnˈkʌmftəbl/','不舒服的','adj.','The bed is uncomfortable.','这床不舒服。'],
  ['convenient','/kənˈviːniənt/','方便的','adj.','This is a convenient time.','这是个方便的时间。'],
  ['inconvenient','/ˌɪnkənˈviːniənt/','不方便的','adj.','This time is inconvenient.','这个时间不方便。'],
  ['hygiene','/ˈhaɪdʒiːn/','卫生','n.','Good hygiene is important.','好的卫生很重要。'],
  ['clean','/kliːn/','干净的','adj.','The room is clean.','房间很干净。'],
  ['dirty','/ˈdɜːrti/','脏的','adj.','The shirt is dirty.','衬衫脏了。'],
  ['dust','/dʌst/','除尘','v.','Dust the shelves.','擦书架上的灰。'],
  ['sweep','/swiːp/','打扫','v.','Sweep the floor.','扫地。'],
  ['wipe','/waɪp/','擦','v.','Wipe the table.','擦桌子。'],
  ['polish','/ˈpɒlɪʃ/','擦亮','v.','Polish the shoes.','擦鞋。'],
  ['tidy','/ˈtaɪdi/','整理','v.','Tidy your room.','整理你的房间。'],
  ['neat','/niːt/','整洁的','adj.','She keeps her room neat.','她保持房间整洁。'],
  ['messy','/ˈmesi/','凌乱的','adj.','His room is messy.','他的房间很乱。'],
  ['trash','/træʃ/','垃圾','n.','Take out the trash.','倒垃圾。'],
  ['garbage','/ˈɡɑːrbɪdʒ/','垃圾','n.','Put the garbage outside.','把垃圾放外面。'],
  ['recycling','/ˌriːˈsaɪklɪŋ/','回收','n.','Put paper in the recycling bin.','把纸放在回收箱里。'],
  ['separate','/ˈseɪprət/','分开','v.','Separate the eggs.','分开鸡蛋。'],
  ['envelope','/ˈenvəloʊp/','信封','n.','Put it in the envelope.','把它放进信封。'],
  ['stamp','/stæmp/','邮票','n.','I need a stamp.','我需要一张邮票。'],
  ['mail','/meɪl/','邮寄','v.','Mail this letter.','寄这封信。'],
  ['delivery','/dɪˈlɪvəri/','递送','n.','The delivery is tomorrow.','递送在明天。'],
  ['friend','/frend/','朋友','n.','She is my best friend.','她是我最好的朋友。'],
  ['guest','/ɡest/','客人','n.','We have a guest today.','我们今天有客人。'],
  ['host','/hoʊst/','主人','n.','She is a good host.','她是个好主人。'],
  ['family','/ˈfæməli/','家庭','n.','My family is large.','我的家庭很大。'],
  ['relative','/ˈrelətɪv/','亲戚','n.','We visit relatives.','我们拜访亲戚。'],
  ['cousin','/ˈkʌzn/','表兄弟姐妹','n.','She is my cousin.','她是我的表妹。'],
  ['nephew','/ˈnefjuː/','侄子','n.','My nephew is cute.','我的侄子很可爱。'],
  ['niece','/niːs/','侄女','n.','My niece is smart.','我的侄女很聪明。'],
  ['uncle','/ˈʌŋkl/','叔叔','n.','My uncle is a doctor.','我叔叔是医生。'],
  ['aunt','/ænt/','阿姨','n.','My aunt is a teacher.','我阿姨是老师。'],
  ['brother','/ˈbrʌðər/','兄弟','n.','My brother is kind.','我的兄弟很善良。'],
  ['sister','/ˈsɪstər/','姐妹','n.','My sister is pretty.','我的姐妹很漂亮。'],
  ['father','/ˈfɑːðər/','父亲','n.','My father is a farmer.','我的父亲是农民。'],
  ['mother','/ˈmʌðər/','母亲','n.','My mother is a nurse.','我的母亲是护士。'],
  ['parent','/ˈperənt/','父母','n.','My parents support me.','我的父母支持我。'],
  ['greet','/ɡriːt/','问候','v.','Greet your teacher.','问候你的老师。'],
  ['invite','/ɪnˈvaɪt/','邀请','v.','Invite her to the party.','邀请她参加聚会。'],
  ['welcome','/ˈwelkəm/','欢迎','v.','Welcome to our home.','欢迎来我家。'],
  ['introduce','/ˌɪntrəˈduːs/','介绍','v.','Let me introduce myself.','让我自我介绍。'],
  ['polite','/pəˈlaɪt/','礼貌的','adj.','Be polite to others.','对他人要有礼貌。'],
  ['rude','/ruːd/','粗鲁的','adj.','Do not be rude.','不要粗鲁。'],
  ['friendly','/ˈfrendli/','友好的','adj.','She is very friendly.','她很友好。'],
  ['hospitable','/hɒˈspɪtəbl/','好客的','adj.','They are very hospitable.','他们非常好客。'],
  ['etiquette','/ˈetɪket/','礼仪','n.','Know proper etiquette.','了解适当的礼仪。'],
  ['manners','/ˈmænərz/','礼貌','n.','Good manners are important.','好的礼貌很重要。'],